"""
Train IVF Success Prediction Model on 5000 Synthetic Records
============================================================

This script trains a Random Forest model on the synthetic IVF dataset
generated by generate_ivf_5000.py.

The model uses 8 features that match the existing prediction API:
- age, bmi, amh, fsh, previous_ivf, stress, sleep_hours, exercise_min

Expected accuracy: 85-92%
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import joblib
import json
import os

# Ensure the models directory exists
os.makedirs("models", exist_ok=True)

def train_ivf_model():
    """Train the IVF success prediction model on synthetic data."""
    
    print("=" * 60)
    print("Training IVF Success Model on 5000 Synthetic Records")
    print("=" * 60)
    
    # Load the synthetic dataset
    dataset_file = "ivf_5000_dataset.csv"
    
    if not os.path.exists(dataset_file):
        print(f"Error: Dataset file '{dataset_file}' not found!")
        print("Please run generate_ivf_5000.py first.")
        return False
    
    print(f"\n📊 Loading dataset from {dataset_file}...")
    df = pd.read_csv(dataset_file)
    
    print(f"Total records: {len(df)}")
    print(f"Success rate: {df['IVF_Success'].mean()*100:.1f}%")
    
    # Prepare features and target
    X = df.drop("IVF_Success", axis=1)
    y = df["IVF_Success"]
    
    print(f"\nFeatures used: {list(X.columns)}")
    
    # Split the data
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42, stratify=y
    )
    
    print(f"\nTraining set size: {len(X_train)}")
    print(f"Test set size: {len(X_test)}")
    
    # Train Random Forest model
    print("\n🌲 Training Random Forest model...")
    model = RandomForestClassifier(
        n_estimators=200,
        max_depth=15,
        min_samples_split=5,
        min_samples_leaf=2,
        random_state=42,
        n_jobs=-1  # Use all CPU cores
    )
    
    model.fit(X_train, y_train)
    
    # Evaluate on test set
    y_pred = model.predict(X_test)
    y_pred_proba = model.predict_proba(X_test)
    
    accuracy = accuracy_score(y_test, y_pred)
    
    print("\n" + "=" * 60)
    print("📈 MODEL EVALUATION RESULTS")
    print("=" * 60)
    print(f"\n✅ Accuracy: {accuracy*100:.2f}%")
    
    print("\n📋 Classification Report:")
    print(classification_report(y_test, y_pred, target_names=['Failure', 'Success']))
    
    print("\n📊 Confusion Matrix:")
    cm = confusion_matrix(y_test, y_pred)
    print(f"  True Negatives: {cm[0][0]}")
    print(f"  False Positives: {cm[0][1]}")
    print(f"  False Negatives: {cm[1][0]}")
    print(f"  True Positives: {cm[1][1]}")
    
    # Feature importance
    print("\n🎯 Feature Importance:")
    feature_importance = pd.DataFrame({
        'feature': X.columns,
        'importance': model.feature_importances_
    }).sort_values('importance', ascending=False)
    
    for idx, row in feature_importance.iterrows():
        print(f"  {row['feature']}: {row['importance']:.4f}")
    
    # Save the model
    model_file = "models/ivf_success_model.pkl"
    joblib.dump(model, model_file)
    print(f"\n💾 Model saved to: {model_file}")
    
    # Save metadata
    metadata = {
        "feature_order": list(X.columns),
        "model": "RandomForestClassifier",
        "accuracy": float(accuracy),
        "training_records": len(df),
        "training_date": pd.Timestamp.now().isoformat(),
        "n_estimators": 200,
        "note": "Trained on 5000 synthetic IVF records"
    }
    
    metadata_file = "models/ivf_model_metadata.json"
    with open(metadata_file, "w") as f:
        json.dump(metadata, f, indent=4)
    
    print(f"📝 Metadata saved to: {metadata_file}")
    
    # Also update the Excel file for consistency
    excel_file = "ivf_datasets.xlsx"
    if os.path.exists(excel_file):
        # Read existing Excel file
        try:
            with pd.ExcelWriter(excel_file, engine='openpyxl', mode='a', if_sheet_exists='replace') as writer:
                df.to_excel(writer, sheet_name="IVF_Success_Data_5000", index=False)
            print(f"📊 Dataset also saved to Excel sheet: IVF_Success_Data_5000")
        except Exception as e:
            print(f"Note: Could not update Excel file: {e}")
    
    print("\n" + "=" * 60)
    print("✅ TRAINING COMPLETE!")
    print("=" * 60)
    
    return True


if __name__ == "__main__":
    success = train_ivf_model()
    if success:
        print("\n🎉 You can now use the model for IVF predictions!")
    else:
        print("\n❌ Training failed. Please check the errors above.")
